//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace hotel.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class hotelRoom
    {
        public int id_number { get; set; }
        public string comfort { get; set; }
        public int numberOfPeople { get; set; }
        public int pricePerDay { get; set; }
        public string status { get; set; }
    }
}
